### ISSUE TITLE
the transforms property seems not to work

### ISSUE THREAD

**Issue by ajeanjean-vivlio** [PiotrKujawa/redux-deep-persist#5]
Hello, 

First of all, thank you for this great package, really helpful !

I've got some troubles with `transforms` property. It seems that it does not apply the transform function on [outbound state](https://github.com/rt2zz/redux-persist#transforms). Maybe my configuration is not set properly ? 

**Here is the configuration:**
<img width="941" alt="Screenshot 2022-07-26 at 17 17 06" src="https://user-images.githubusercontent.com/100350680/181045298-d330e300-a65b-44c1-ac0d-1e868aff7c9a.png">

**Here is my transforms:** 
<img width="941" alt="Screenshot 2022-07-26 at 17 18 01" src="https://user-images.githubusercontent.com/100350680/181045416-ade135a3-a920-4421-b18c-dfe9c7a4b213.png">

**Reseller.fromCloud(data)** is a function which instanciate a new Reseller class. 

But after verification, no class is instantiated...

Could you help me please ?

Thank you for your answer

**Comment by PiotrKujawa** [comment]
Hi @ajeanjean-vivlio, thank you for catching this up. I may take a look at this tomorrow.

**Comment by ajeanjean-vivlio** [comment]
Hi @PiotrKujawa , thanks for your answer. What I can see today by comparing the two configurations is that the rehydration of the store by the transforms property seems to be faster using the `redux-persist` configuration than using the `redux-deep-persist` configuration. I don't know why it takes more time but thank you for your help.

**Comment by PiotrKujawa** [comment]
Well, slower rehydration is expected since redux-deep-persist is also based on transforms, and lots of operations are done during rehydration. But I also will take performance into account when checking your issue.

**Comment by ajeanjean-vivlio** [comment]
Thank you for your answer, it helps me understand why it takes a little longer. In the above case, in the first render, the data is not transformed, and in the second render I get the data transformed into class type. This takes just a few milliseconds, but it caused my application to crash, because the expected type was not of the class Reseller in the first render.

Thank you for your help.

**Comment by PiotrKujawa** [comment]
Hi @ajeanjean-vivlio, sorry I didn't get back to you yesterday but I had a lot of work.
Looking at your configuration I see you still use a nested config which is fine but you must be very careful when naming your root reducer key in your nested config and then whitelist reducer key in your transform method.

I took a look at custom transforms, and how they work together with redux-deep-persist and I don't see any issues. Everything works as expected. The problem may be with your configuration. Resellers transform will work for `auth.resellers` key in your `rootReducer`. If you have resellers at any different level then your transform won't be invoked.
I would suggest creating a flat config that would look cleaner and you could define a blacklist or whitelist with a little deeper nesting level. Of course, if the performance of saving a few milliseconds is important to you I would keep it as you have.

Please let me know if this was helpful for you.

**Comment by ajeanjean-vivlio** [comment]
Hi @PiotrKujawa , thank you very much for your help and time. Finally we found another way which fits our needs. I think as you said that the issue was on our side, but I did not understand yet why we receive transformed data with a little rendering shift.

Thank you for your answer and your work.
